// @effect-diagnostics nodeBuiltinImport:off
/**
 * Theme CSS / config content produced by design-system install recipes.
 * Mirrors output from shadcn init, Tailwind @theme, and baseline modern-starter tokens.
 */
import type { AutoDsmWorkspaceStarterId } from "@t3tools/contracts";

/** Canonical shadcn-style semantic CSS variables (light + dark). */
export const SHADCN_THEME_CSS = `:root {
  --background: oklch(1 0 0);
  --foreground: oklch(0.145 0 0);
  --card: oklch(1 0 0);
  --card-foreground: oklch(0.145 0 0);
  --popover: oklch(1 0 0);
  --popover-foreground: oklch(0.145 0 0);
  --primary: oklch(0.511 0.262 276.966);
  --primary-foreground: oklch(0.985 0 0);
  --secondary: oklch(0.967 0.001 286.375);
  --secondary-foreground: oklch(0.21 0.006 285.885);
  --muted: oklch(0.967 0.001 286.375);
  --muted-foreground: oklch(0.552 0.016 285.938);
  --accent: oklch(0.967 0.001 286.375);
  --accent-foreground: oklch(0.21 0.006 285.885);
  --destructive: oklch(0.577 0.245 27.325);
  --destructive-foreground: oklch(0.985 0 0);
  --border: oklch(0.92 0.004 286.32);
  --input: oklch(0.92 0.004 286.32);
  --ring: oklch(0.511 0.262 276.966);
  --radius: 0.625rem;
  --font-sans: ui-sans-serif, system-ui, sans-serif;
  --font-size-base: 16px;
  --letter-spacing-normal: 0em;
  --space-1: 0.25rem;
  --space-2: 0.5rem;
  --space-3: 0.75rem;
  --space-4: 1rem;
  --space-6: 1.5rem;
  --space-8: 2rem;
  --duration-fast: 120ms;
  --duration-normal: 200ms;
  --ease-default: cubic-bezier(0.4, 0, 0.2, 1);
}

.dark {
  --background: oklch(0.145 0 0);
  --foreground: oklch(0.985 0 0);
  --card: oklch(0.205 0 0);
  --card-foreground: oklch(0.985 0 0);
  --popover: oklch(0.205 0 0);
  --popover-foreground: oklch(0.985 0 0);
  --primary: oklch(0.627 0.265 303.9);
  --primary-foreground: oklch(0.985 0 0);
  --secondary: oklch(0.269 0 0);
  --secondary-foreground: oklch(0.985 0 0);
  --muted: oklch(0.269 0 0);
  --muted-foreground: oklch(0.708 0 0);
  --accent: oklch(0.269 0 0);
  --accent-foreground: oklch(0.985 0 0);
  --destructive: oklch(0.704 0.191 22.216);
  --destructive-foreground: oklch(0.985 0 0);
  --border: oklch(1 0 0 / 10%);
  --input: oklch(1 0 0 / 15%);
  --ring: oklch(0.627 0.265 303.9);
}
`;

export const TAILWIND_THEME_CSS = `@import "tailwindcss";

@theme {
  --color-brand-50: oklch(0.985 0.02 280);
  --color-brand-500: oklch(0.511 0.262 276.966);
  --color-brand-900: oklch(0.25 0.08 280);
  --font-sans: ui-sans-serif, system-ui, sans-serif;
  --spacing-4: 1rem;
  --spacing-8: 2rem;
  --radius-md: 0.375rem;
  --duration-fast: 120ms;
}

:root {
  --primary: var(--color-brand-500);
  --background: oklch(1 0 0);
  --foreground: oklch(0.145 0 0);
  --space-4: var(--spacing-4);
  --space-8: var(--spacing-8);
  --radius: var(--radius-md);
  --duration-fast: 120ms;
}

.dark {
  --primary: oklch(0.627 0.265 303.9);
  --background: oklch(0.145 0 0);
  --foreground: oklch(0.985 0 0);
}
`;

export const MODERN_STARTER_THEME_CSS = `@import "tailwindcss";

:root {
  --background: #ffffff;
  --foreground: #0f172a;
  --primary: #6366f1;
  --primary-foreground: #ffffff;
  --muted: #f1f5f9;
  --muted-foreground: #64748b;
  --border: #e2e8f0;
  --radius: 0.5rem;
  --font-sans: Inter, ui-sans-serif, system-ui, sans-serif;
  --font-size-base: 16px;
  --space-2: 0.5rem;
  --space-4: 1rem;
  --space-8: 2rem;
  --duration-fast: 150ms;
}

.dark {
  --background: #0f172a;
  --foreground: #f8fafc;
  --primary: #818cf8;
  --primary-foreground: #0f172a;
  --muted: #1e293b;
  --muted-foreground: #94a3b8;
  --border: #334155;
}
`;

/** MUI / Chakra workspaces share CSS vars consumed by preview theme shells. */
export const MUI_CHAKRA_THEME_CSS = `:root {
  --primary: #7c3aed;
  --primary-foreground: #ffffff;
  --secondary: #64748b;
  --background: #ffffff;
  --foreground: #0f172a;
  --muted: #f1f5f9;
  --border: #e2e8f0;
  --radius: 8px;
  --font-sans: Roboto, ui-sans-serif, system-ui, sans-serif;
  --font-size-base: 16px;
  --space-2: 8px;
  --space-4: 16px;
  --duration-fast: 120ms;
}

.dark {
  --primary: #a78bfa;
  --primary-foreground: #1e1b4b;
  --background: #0f172a;
  --foreground: #f8fafc;
  --muted: #1e293b;
  --border: #334155;
}
`;

export const MUI_THEME_TS = `import { createTheme } from "@mui/material/styles";

/** Generated by AutoDSM design-system install — palette reads CSS custom properties. */
export const autodsmMuiTheme = createTheme({
  palette: {
    mode: "light",
    primary: { main: "var(--primary)" },
    secondary: { main: "var(--secondary)" },
    background: { default: "var(--background)", paper: "var(--background)" },
    text: { primary: "var(--foreground)" },
  },
  shape: { borderRadius: 8 },
  typography: {
    fontFamily: "var(--font-sans)",
    fontSize: 16,
  },
});
`;

export const CHAKRA_THEME_TS = `import { extendTheme } from "@chakra-ui/react";

/** Generated by AutoDSM design-system install — colors mirror CSS custom properties. */
export const autodsmChakraTheme = extendTheme({
  colors: {
    brand: {
      500: "var(--primary)",
    },
  },
  fonts: {
    body: "var(--font-sans)",
  },
  radii: {
    md: "var(--radius)",
  },
});
`;

export function themeCssForStarter(starterId: AutoDsmWorkspaceStarterId): string {
  switch (starterId) {
    case "shadcn-ui":
      return `@import "tailwindcss";\n\n${SHADCN_THEME_CSS}`;
    case "tailwind-css":
      return TAILWIND_THEME_CSS;
    case "modern-starter":
      return MODERN_STARTER_THEME_CSS;
    case "mui":
    case "chakra-ui":
      return MUI_CHAKRA_THEME_CSS;
    default:
      return MODERN_STARTER_THEME_CSS;
  }
}
