/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PairRouteImport } from './routes/pair'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ChatRouteImport } from './routes/_chat'
import { Route as ChatIndexRouteImport } from './routes/_chat.index'
import { Route as SettingsSourceControlRouteImport } from './routes/settings.source-control'
import { Route as SettingsProvidersRouteImport } from './routes/settings.providers'
import { Route as SettingsKeybindingsRouteImport } from './routes/settings.keybindings'
import { Route as SettingsGeneralRouteImport } from './routes/settings.general'
import { Route as SettingsDiagnosticsRouteImport } from './routes/settings.diagnostics'
import { Route as SettingsConnectionsRouteImport } from './routes/settings.connections'
import { Route as SettingsArchivedRouteImport } from './routes/settings.archived'
import { Route as OnboardingWelcomeRouteImport } from './routes/onboarding.welcome'
import { Route as OnboardingNameRouteImport } from './routes/onboarding.name'
import { Route as OnboardingMethodRouteImport } from './routes/onboarding.method'
import { Route as OnboardingLoadingRouteImport } from './routes/onboarding.loading'
import { Route as OnboardingLibraryRouteImport } from './routes/onboarding.library'
import { Route as OnboardingCreateRouteImport } from './routes/onboarding.create'
import { Route as OnboardingBriefRouteImport } from './routes/onboarding.brief'
import { Route as OnboardingBetaRouteImport } from './routes/onboarding.beta'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ChatPreviewComponentsSandboxRouteImport } from './routes/_chat.preview-components-sandbox'
import { Route as ChatHomeRouteImport } from './routes/_chat.home'
import { Route as ChatDesignTokensRouteImport } from './routes/_chat.design-tokens'
import { Route as ChatDesignComponentsRouteImport } from './routes/_chat.design-components'
import { Route as ChatComponentPreviewRuntimeRouteImport } from './routes/_chat.component-preview-runtime'
import { Route as ChatDraftDraftIdRouteImport } from './routes/_chat.draft.$draftId'
import { Route as ChatEnvironmentIdThreadIdRouteImport } from './routes/_chat.$environmentId.$threadId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PairRoute = PairRouteImport.update({
  id: '/pair',
  path: '/pair',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/_chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const SettingsSourceControlRoute = SettingsSourceControlRouteImport.update({
  id: '/source-control',
  path: '/source-control',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsProvidersRoute = SettingsProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsKeybindingsRoute = SettingsKeybindingsRouteImport.update({
  id: '/keybindings',
  path: '/keybindings',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsGeneralRoute = SettingsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsDiagnosticsRoute = SettingsDiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsConnectionsRoute = SettingsConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsArchivedRoute = SettingsArchivedRouteImport.update({
  id: '/archived',
  path: '/archived',
  getParentRoute: () => SettingsRoute,
} as any)
const OnboardingWelcomeRoute = OnboardingWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingNameRoute = OnboardingNameRouteImport.update({
  id: '/name',
  path: '/name',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingMethodRoute = OnboardingMethodRouteImport.update({
  id: '/method',
  path: '/method',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingLoadingRoute = OnboardingLoadingRouteImport.update({
  id: '/loading',
  path: '/loading',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingLibraryRoute = OnboardingLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingCreateRoute = OnboardingCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingBriefRoute = OnboardingBriefRouteImport.update({
  id: '/brief',
  path: '/brief',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingBetaRoute = OnboardingBetaRouteImport.update({
  id: '/beta',
  path: '/beta',
  getParentRoute: () => OnboardingRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatPreviewComponentsSandboxRoute =
  ChatPreviewComponentsSandboxRouteImport.update({
    id: '/preview-components-sandbox',
    path: '/preview-components-sandbox',
    getParentRoute: () => ChatRoute,
  } as any)
const ChatHomeRoute = ChatHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => ChatRoute,
} as any)
const ChatDesignTokensRoute = ChatDesignTokensRouteImport.update({
  id: '/design-tokens',
  path: '/design-tokens',
  getParentRoute: () => ChatRoute,
} as any)
const ChatDesignComponentsRoute = ChatDesignComponentsRouteImport.update({
  id: '/design-components',
  path: '/design-components',
  getParentRoute: () => ChatRoute,
} as any)
const ChatComponentPreviewRuntimeRoute =
  ChatComponentPreviewRuntimeRouteImport.update({
    id: '/component-preview-runtime',
    path: '/component-preview-runtime',
    getParentRoute: () => ChatRoute,
  } as any)
const ChatDraftDraftIdRoute = ChatDraftDraftIdRouteImport.update({
  id: '/draft/$draftId',
  path: '/draft/$draftId',
  getParentRoute: () => ChatRoute,
} as any)
const ChatEnvironmentIdThreadIdRoute =
  ChatEnvironmentIdThreadIdRouteImport.update({
    id: '/$environmentId/$threadId',
    path: '/$environmentId/$threadId',
    getParentRoute: () => ChatRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ChatIndexRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/pair': typeof PairRoute
  '/settings': typeof SettingsRouteWithChildren
  '/component-preview-runtime': typeof ChatComponentPreviewRuntimeRoute
  '/design-components': typeof ChatDesignComponentsRoute
  '/design-tokens': typeof ChatDesignTokensRoute
  '/home': typeof ChatHomeRoute
  '/preview-components-sandbox': typeof ChatPreviewComponentsSandboxRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/onboarding/beta': typeof OnboardingBetaRoute
  '/onboarding/brief': typeof OnboardingBriefRoute
  '/onboarding/create': typeof OnboardingCreateRoute
  '/onboarding/library': typeof OnboardingLibraryRoute
  '/onboarding/loading': typeof OnboardingLoadingRoute
  '/onboarding/method': typeof OnboardingMethodRoute
  '/onboarding/name': typeof OnboardingNameRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/diagnostics': typeof SettingsDiagnosticsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/keybindings': typeof SettingsKeybindingsRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/settings/source-control': typeof SettingsSourceControlRoute
  '/$environmentId/$threadId': typeof ChatEnvironmentIdThreadIdRoute
  '/draft/$draftId': typeof ChatDraftDraftIdRoute
}
export interface FileRoutesByTo {
  '/onboarding': typeof OnboardingRouteWithChildren
  '/pair': typeof PairRoute
  '/settings': typeof SettingsRouteWithChildren
  '/component-preview-runtime': typeof ChatComponentPreviewRuntimeRoute
  '/design-components': typeof ChatDesignComponentsRoute
  '/design-tokens': typeof ChatDesignTokensRoute
  '/home': typeof ChatHomeRoute
  '/preview-components-sandbox': typeof ChatPreviewComponentsSandboxRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/onboarding/beta': typeof OnboardingBetaRoute
  '/onboarding/brief': typeof OnboardingBriefRoute
  '/onboarding/create': typeof OnboardingCreateRoute
  '/onboarding/library': typeof OnboardingLibraryRoute
  '/onboarding/loading': typeof OnboardingLoadingRoute
  '/onboarding/method': typeof OnboardingMethodRoute
  '/onboarding/name': typeof OnboardingNameRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/diagnostics': typeof SettingsDiagnosticsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/keybindings': typeof SettingsKeybindingsRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/settings/source-control': typeof SettingsSourceControlRoute
  '/': typeof ChatIndexRoute
  '/$environmentId/$threadId': typeof ChatEnvironmentIdThreadIdRoute
  '/draft/$draftId': typeof ChatDraftDraftIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_chat': typeof ChatRouteWithChildren
  '/onboarding': typeof OnboardingRouteWithChildren
  '/pair': typeof PairRoute
  '/settings': typeof SettingsRouteWithChildren
  '/_chat/component-preview-runtime': typeof ChatComponentPreviewRuntimeRoute
  '/_chat/design-components': typeof ChatDesignComponentsRoute
  '/_chat/design-tokens': typeof ChatDesignTokensRoute
  '/_chat/home': typeof ChatHomeRoute
  '/_chat/preview-components-sandbox': typeof ChatPreviewComponentsSandboxRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/onboarding/beta': typeof OnboardingBetaRoute
  '/onboarding/brief': typeof OnboardingBriefRoute
  '/onboarding/create': typeof OnboardingCreateRoute
  '/onboarding/library': typeof OnboardingLibraryRoute
  '/onboarding/loading': typeof OnboardingLoadingRoute
  '/onboarding/method': typeof OnboardingMethodRoute
  '/onboarding/name': typeof OnboardingNameRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/diagnostics': typeof SettingsDiagnosticsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/keybindings': typeof SettingsKeybindingsRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/settings/source-control': typeof SettingsSourceControlRoute
  '/_chat/': typeof ChatIndexRoute
  '/_chat/$environmentId/$threadId': typeof ChatEnvironmentIdThreadIdRoute
  '/_chat/draft/$draftId': typeof ChatDraftDraftIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/pair'
    | '/settings'
    | '/component-preview-runtime'
    | '/design-components'
    | '/design-tokens'
    | '/home'
    | '/preview-components-sandbox'
    | '/auth/callback'
    | '/onboarding/beta'
    | '/onboarding/brief'
    | '/onboarding/create'
    | '/onboarding/library'
    | '/onboarding/loading'
    | '/onboarding/method'
    | '/onboarding/name'
    | '/onboarding/welcome'
    | '/settings/archived'
    | '/settings/connections'
    | '/settings/diagnostics'
    | '/settings/general'
    | '/settings/keybindings'
    | '/settings/providers'
    | '/settings/source-control'
    | '/$environmentId/$threadId'
    | '/draft/$draftId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/onboarding'
    | '/pair'
    | '/settings'
    | '/component-preview-runtime'
    | '/design-components'
    | '/design-tokens'
    | '/home'
    | '/preview-components-sandbox'
    | '/auth/callback'
    | '/onboarding/beta'
    | '/onboarding/brief'
    | '/onboarding/create'
    | '/onboarding/library'
    | '/onboarding/loading'
    | '/onboarding/method'
    | '/onboarding/name'
    | '/onboarding/welcome'
    | '/settings/archived'
    | '/settings/connections'
    | '/settings/diagnostics'
    | '/settings/general'
    | '/settings/keybindings'
    | '/settings/providers'
    | '/settings/source-control'
    | '/'
    | '/$environmentId/$threadId'
    | '/draft/$draftId'
  id:
    | '__root__'
    | '/_chat'
    | '/onboarding'
    | '/pair'
    | '/settings'
    | '/_chat/component-preview-runtime'
    | '/_chat/design-components'
    | '/_chat/design-tokens'
    | '/_chat/home'
    | '/_chat/preview-components-sandbox'
    | '/auth/callback'
    | '/onboarding/beta'
    | '/onboarding/brief'
    | '/onboarding/create'
    | '/onboarding/library'
    | '/onboarding/loading'
    | '/onboarding/method'
    | '/onboarding/name'
    | '/onboarding/welcome'
    | '/settings/archived'
    | '/settings/connections'
    | '/settings/diagnostics'
    | '/settings/general'
    | '/settings/keybindings'
    | '/settings/providers'
    | '/settings/source-control'
    | '/_chat/'
    | '/_chat/$environmentId/$threadId'
    | '/_chat/draft/$draftId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ChatRoute: typeof ChatRouteWithChildren
  OnboardingRoute: typeof OnboardingRouteWithChildren
  PairRoute: typeof PairRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pair': {
      id: '/pair'
      path: '/pair'
      fullPath: '/pair'
      preLoaderRoute: typeof PairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat': {
      id: '/_chat'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/': {
      id: '/_chat/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/settings/source-control': {
      id: '/settings/source-control'
      path: '/source-control'
      fullPath: '/settings/source-control'
      preLoaderRoute: typeof SettingsSourceControlRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/providers': {
      id: '/settings/providers'
      path: '/providers'
      fullPath: '/settings/providers'
      preLoaderRoute: typeof SettingsProvidersRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/keybindings': {
      id: '/settings/keybindings'
      path: '/keybindings'
      fullPath: '/settings/keybindings'
      preLoaderRoute: typeof SettingsKeybindingsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/general': {
      id: '/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsGeneralRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/diagnostics': {
      id: '/settings/diagnostics'
      path: '/diagnostics'
      fullPath: '/settings/diagnostics'
      preLoaderRoute: typeof SettingsDiagnosticsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/connections': {
      id: '/settings/connections'
      path: '/connections'
      fullPath: '/settings/connections'
      preLoaderRoute: typeof SettingsConnectionsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/archived': {
      id: '/settings/archived'
      path: '/archived'
      fullPath: '/settings/archived'
      preLoaderRoute: typeof SettingsArchivedRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/onboarding/welcome': {
      id: '/onboarding/welcome'
      path: '/welcome'
      fullPath: '/onboarding/welcome'
      preLoaderRoute: typeof OnboardingWelcomeRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/name': {
      id: '/onboarding/name'
      path: '/name'
      fullPath: '/onboarding/name'
      preLoaderRoute: typeof OnboardingNameRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/method': {
      id: '/onboarding/method'
      path: '/method'
      fullPath: '/onboarding/method'
      preLoaderRoute: typeof OnboardingMethodRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/loading': {
      id: '/onboarding/loading'
      path: '/loading'
      fullPath: '/onboarding/loading'
      preLoaderRoute: typeof OnboardingLoadingRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/library': {
      id: '/onboarding/library'
      path: '/library'
      fullPath: '/onboarding/library'
      preLoaderRoute: typeof OnboardingLibraryRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/create': {
      id: '/onboarding/create'
      path: '/create'
      fullPath: '/onboarding/create'
      preLoaderRoute: typeof OnboardingCreateRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/brief': {
      id: '/onboarding/brief'
      path: '/brief'
      fullPath: '/onboarding/brief'
      preLoaderRoute: typeof OnboardingBriefRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/beta': {
      id: '/onboarding/beta'
      path: '/beta'
      fullPath: '/onboarding/beta'
      preLoaderRoute: typeof OnboardingBetaRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/preview-components-sandbox': {
      id: '/_chat/preview-components-sandbox'
      path: '/preview-components-sandbox'
      fullPath: '/preview-components-sandbox'
      preLoaderRoute: typeof ChatPreviewComponentsSandboxRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/home': {
      id: '/_chat/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof ChatHomeRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/design-tokens': {
      id: '/_chat/design-tokens'
      path: '/design-tokens'
      fullPath: '/design-tokens'
      preLoaderRoute: typeof ChatDesignTokensRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/design-components': {
      id: '/_chat/design-components'
      path: '/design-components'
      fullPath: '/design-components'
      preLoaderRoute: typeof ChatDesignComponentsRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/component-preview-runtime': {
      id: '/_chat/component-preview-runtime'
      path: '/component-preview-runtime'
      fullPath: '/component-preview-runtime'
      preLoaderRoute: typeof ChatComponentPreviewRuntimeRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/draft/$draftId': {
      id: '/_chat/draft/$draftId'
      path: '/draft/$draftId'
      fullPath: '/draft/$draftId'
      preLoaderRoute: typeof ChatDraftDraftIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/$environmentId/$threadId': {
      id: '/_chat/$environmentId/$threadId'
      path: '/$environmentId/$threadId'
      fullPath: '/$environmentId/$threadId'
      preLoaderRoute: typeof ChatEnvironmentIdThreadIdRouteImport
      parentRoute: typeof ChatRoute
    }
  }
}

interface ChatRouteChildren {
  ChatComponentPreviewRuntimeRoute: typeof ChatComponentPreviewRuntimeRoute
  ChatDesignComponentsRoute: typeof ChatDesignComponentsRoute
  ChatDesignTokensRoute: typeof ChatDesignTokensRoute
  ChatHomeRoute: typeof ChatHomeRoute
  ChatPreviewComponentsSandboxRoute: typeof ChatPreviewComponentsSandboxRoute
  ChatIndexRoute: typeof ChatIndexRoute
  ChatEnvironmentIdThreadIdRoute: typeof ChatEnvironmentIdThreadIdRoute
  ChatDraftDraftIdRoute: typeof ChatDraftDraftIdRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatComponentPreviewRuntimeRoute: ChatComponentPreviewRuntimeRoute,
  ChatDesignComponentsRoute: ChatDesignComponentsRoute,
  ChatDesignTokensRoute: ChatDesignTokensRoute,
  ChatHomeRoute: ChatHomeRoute,
  ChatPreviewComponentsSandboxRoute: ChatPreviewComponentsSandboxRoute,
  ChatIndexRoute: ChatIndexRoute,
  ChatEnvironmentIdThreadIdRoute: ChatEnvironmentIdThreadIdRoute,
  ChatDraftDraftIdRoute: ChatDraftDraftIdRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

interface OnboardingRouteChildren {
  OnboardingBetaRoute: typeof OnboardingBetaRoute
  OnboardingBriefRoute: typeof OnboardingBriefRoute
  OnboardingCreateRoute: typeof OnboardingCreateRoute
  OnboardingLibraryRoute: typeof OnboardingLibraryRoute
  OnboardingLoadingRoute: typeof OnboardingLoadingRoute
  OnboardingMethodRoute: typeof OnboardingMethodRoute
  OnboardingNameRoute: typeof OnboardingNameRoute
  OnboardingWelcomeRoute: typeof OnboardingWelcomeRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingBetaRoute: OnboardingBetaRoute,
  OnboardingBriefRoute: OnboardingBriefRoute,
  OnboardingCreateRoute: OnboardingCreateRoute,
  OnboardingLibraryRoute: OnboardingLibraryRoute,
  OnboardingLoadingRoute: OnboardingLoadingRoute,
  OnboardingMethodRoute: OnboardingMethodRoute,
  OnboardingNameRoute: OnboardingNameRoute,
  OnboardingWelcomeRoute: OnboardingWelcomeRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

interface SettingsRouteChildren {
  SettingsArchivedRoute: typeof SettingsArchivedRoute
  SettingsConnectionsRoute: typeof SettingsConnectionsRoute
  SettingsDiagnosticsRoute: typeof SettingsDiagnosticsRoute
  SettingsGeneralRoute: typeof SettingsGeneralRoute
  SettingsKeybindingsRoute: typeof SettingsKeybindingsRoute
  SettingsProvidersRoute: typeof SettingsProvidersRoute
  SettingsSourceControlRoute: typeof SettingsSourceControlRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsArchivedRoute: SettingsArchivedRoute,
  SettingsConnectionsRoute: SettingsConnectionsRoute,
  SettingsDiagnosticsRoute: SettingsDiagnosticsRoute,
  SettingsGeneralRoute: SettingsGeneralRoute,
  SettingsKeybindingsRoute: SettingsKeybindingsRoute,
  SettingsProvidersRoute: SettingsProvidersRoute,
  SettingsSourceControlRoute: SettingsSourceControlRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ChatRoute: ChatRouteWithChildren,
  OnboardingRoute: OnboardingRouteWithChildren,
  PairRoute: PairRoute,
  SettingsRoute: SettingsRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
