import { extendTheme } from "@chakra-ui/react";

/** Generated by AutoDSM design-system install — colors mirror CSS custom properties. */
export const autodsmChakraTheme = extendTheme({
  colors: {
    brand: {
      500: "var(--primary)",
    },
  },
  fonts: {
    body: "var(--font-sans)",
  },
  radii: {
    md: "var(--radius)",
  },
});
