import { createTheme } from "@mui/material/styles";

/** Generated by AutoDSM design-system install — palette reads CSS custom properties. */
export const autodsmMuiTheme = createTheme({
  palette: {
    mode: "light",
    primary: { main: "var(--primary)" },
    secondary: { main: "var(--secondary)" },
    background: { default: "var(--background)", paper: "var(--background)" },
    text: { primary: "var(--foreground)" },
  },
  shape: { borderRadius: 8 },
  typography: {
    fontFamily: "var(--font-sans)",
    fontSize: 16,
  },
});
